name: Continuous Integration with DockerHub

on:
  push:
    branches: main

jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest
          build-args: |
            arg1=value1
            arg2=value2
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Show Response
        run: echo ${{ steps.myRequest.outputs.response }}
      - name: Make Request
        id: myRequest
        uses: satak/webrequest-action@master
        env:
            DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        with:
          url: ${{ secrets.SERVER_IP_ADRESS }}
          method: POST
          payload: '{"repo": "${{ env.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest"}, {"params": "${{ secrets.PARAMS }}"}'
